;;; emacs-a11y-setup-handoff-tests.el --- ERT handoff tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'emacs-a11y-setup)

(ert-deftest emacs-a11y-setup-handoff-valid-contract ()
  (let* ((tmp (make-temp-file "a11y-handoff-" t))
         (payload `((contract_version . "1.0")
                    (platform . "macos")
                    (bootstrap_mode . "recommended")
                    (workspace_path . ,tmp)))
         (result (emacs-a11y-setup-process-handoff payload)))
    (should (plist-get result :ok))
    (should (equal (plist-get (plist-get result :contract) :workspace_path) tmp))))

(ert-deftest emacs-a11y-setup-handoff-missing-contract-version ()
  (let* ((tmp (make-temp-file "a11y-handoff-" t))
         (payload `((platform . "macos")
                    (bootstrap_mode . "recommended")
                    (workspace_path . ,tmp)))
         (result (emacs-a11y-setup-process-handoff payload)))
    (should-not (plist-get result :ok))
    (should (seq-some (lambda (e) (string-match-p "contract_version" e))
                      (plist-get result :errors)))))

(ert-deftest emacs-a11y-setup-handoff-incompatible-version ()
  (let* ((tmp (make-temp-file "a11y-handoff-" t))
         (payload `((contract_version . "2.0")
                    (platform . "macos")
                    (bootstrap_mode . "recommended")
                    (workspace_path . ,tmp)))
         (result (emacs-a11y-setup-process-handoff payload)))
    (should-not (plist-get result :ok))
    (should (seq-some (lambda (e) (string-match-p "1\\.x" e))
                      (plist-get result :errors)))))

(ert-deftest emacs-a11y-setup-handoff-missing-workspace-path ()
  (let* ((payload '((contract_version . "1.0")
                    (platform . "macos")
                    (bootstrap_mode . "recommended")))
         (result (emacs-a11y-setup-process-handoff payload)))
    (should-not (plist-get result :ok))
    (should (seq-some (lambda (e) (string-match-p "workspace_path" e))
                      (plist-get result :errors)))))

(ert-deftest emacs-a11y-setup-handoff-optional-fields-missing-safe ()
  (let* ((tmp (make-temp-file "a11y-handoff-" t))
         (payload `((contract_version . "1.0")
                    (platform . "unknown")
                    (bootstrap_mode . "minimal")
                    (workspace_path . ,tmp)))
         (result (emacs-a11y-setup-process-handoff payload)))
    (should (plist-get result :ok))
    (should (consp (plist-get result :warnings)))))

(provide 'emacs-a11y-setup-handoff-tests)
