;;; emacs-a11y-setup-workspace-tests.el --- ERT workspace tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'emacs-a11y-setup)

(ert-deftest emacs-a11y-setup-workspace-create-in-temp-dir ()
  (let* ((tmp (make-temp-file "a11y-ws-" t))
         (result (emacs-a11y-setup-create-workspace :workspace-path tmp)))
    (should (plist-get result :valid))
    (should (file-exists-p (expand-file-name "init.el" tmp)))
    (should (file-exists-p (expand-file-name "early-init.el" tmp)))
    (should (file-exists-p (expand-file-name "custom.el" tmp)))
    (dolist (dir '("config" "profiles" "logs" "reports" "backups"))
      (should (file-directory-p (expand-file-name dir tmp))))))

(ert-deftest emacs-a11y-setup-workspace-idempotent ()
  (let* ((tmp (make-temp-file "a11y-ws-idem-" t))
         (first (emacs-a11y-setup-create-workspace :workspace-path tmp))
         (second (emacs-a11y-setup-create-workspace :workspace-path tmp)))
    (should (plist-get first :valid))
    (should (plist-get second :valid))))

(ert-deftest emacs-a11y-setup-workspace-preserves-personal-config ()
  (let* ((tmp-home (make-temp-file "a11y-home-" t))
         (user-emacs-directory (expand-file-name ".emacs.d" tmp-home))
         (config-emacs (expand-file-name ".config/emacs" tmp-home)))
    (make-directory user-emacs-directory t)
    (make-directory config-emacs t)
    (with-temp-file (expand-file-name "init.el" user-emacs-directory)
      (insert "personal"))
    (with-temp-file (expand-file-name "init.el" config-emacs)
      (insert "personal"))
    (let ((target (make-temp-file "a11y-ws-safe-" t)))
      (emacs-a11y-setup-create-workspace :workspace-path target)
      (should (string= (with-temp-buffer
                         (insert-file-contents (expand-file-name "init.el" user-emacs-directory))
                         (buffer-string))
                       "personal"))
      (should (string= (with-temp-buffer
                         (insert-file-contents (expand-file-name "init.el" config-emacs))
                         (buffer-string))
                       "personal")))))

(ert-deftest emacs-a11y-setup-workspace-repairs-partial-structure ()
  (let* ((tmp (make-temp-file "a11y-ws-repair-" t)))
    (make-directory (expand-file-name "config" tmp) t)
    (emacs-a11y-setup-create-workspace :workspace-path tmp)
    (dolist (dir '("profiles" "logs" "reports" "backups"))
      (should (file-directory-p (expand-file-name dir tmp))))
    (should (file-exists-p (expand-file-name "init.el" tmp)))))

(ert-deftest emacs-a11y-setup-workspace-init-guides-load-path ()
  (let* ((tmp (make-temp-file "a11y-ws-guide-" t))
         (_result (emacs-a11y-setup-create-workspace :workspace-path tmp))
         (init-file (expand-file-name "init.el" tmp))
         (content (with-temp-buffer
                    (insert-file-contents init-file)
                    (buffer-string))))
    (should (string-match-p "EMACSLOADPATH" content))
    (should (string-match-p "EMACS_A11Y_SETUP_PACKAGE_DIR" content))))

(ert-deftest emacs-a11y-setup-workspace-default-path-uses-root-home ()
  (let* ((tmp-home (make-temp-file "a11y-home-root-" t))
         (process-environment (copy-sequence process-environment))
         (emacs-a11y-setup-home-path nil)
         (emacs-a11y-setup-workspace-path nil)
         (system-type 'gnu/linux))
    (setenv "HOME" tmp-home)
    (setenv "EMACS_A11Y_HOME" nil)
    (setenv "EMACS_A11Y_DEFAULT_WORKSPACE" nil)
    (should (equal (emacs-a11y-setup-resolve-home-path)
                   (expand-file-name ".emacs-a11y" tmp-home)))
    (should (equal (emacs-a11y-setup-resolve-workspace-path)
                   (expand-file-name ".emacs-a11y/workspace" tmp-home)))))

(ert-deftest emacs-a11y-setup-workspace-env-overrides-defaults ()
  (let* ((tmp-root (make-temp-file "a11y-root-" t))
         (tmp-workspace (make-temp-file "a11y-ws-env-" t))
         (process-environment (copy-sequence process-environment))
         (emacs-a11y-setup-home-path nil)
         (emacs-a11y-setup-workspace-path nil))
    (setenv "EMACS_A11Y_HOME" tmp-root)
    (setenv "EMACS_A11Y_DEFAULT_WORKSPACE" tmp-workspace)
    (should (equal (emacs-a11y-setup-resolve-home-path)
                   (expand-file-name tmp-root)))
    (should (equal (emacs-a11y-setup-resolve-workspace-path)
                   (expand-file-name tmp-workspace)))))

(provide 'emacs-a11y-setup-workspace-tests)
